FROM php:{{VIBE4DOCK_PHP_VERSION}}-cli-bookworm

RUN apt-get update && apt-get install -y --no-install-recommends \
    docker.io \
    git \
  && rm -rf /var/lib/apt/lists/*

WORKDIR /app/docker/tools

COPY . ./

EXPOSE 8090

CMD ["php", "-d", "upload_max_filesize=100M", "-d", "post_max_size=120M", "-d", "max_execution_time=300", "-S", "0.0.0.0:8090", "index.php"]
