FROM php:{{VIBE4DOCK_PHP_VERSION}}-cli-bookworm

RUN apt-get update && apt-get install -y --no-install-recommends \
    docker.io \
    git \
  && rm -rf /var/lib/apt/lists/*

WORKDIR /app/docker/tools

COPY . ./

EXPOSE 8090

CMD ["php", "-S", "0.0.0.0:8090", "index.php"]